### ISSUE TITLE
您好！请问

### ISSUE THREAD

**Issue by jinyaqing** [njuHan/MPTCP-Deep-Reinforcement-Learning#1]
您好！现在正在做MPTCP方面的研究，发现了您的代码，请问这个是在哪个平台上运行的？需要装哪些软件呢？感谢！

**Comment by njuHan** [comment]
你好，这些代码已经不维护和使用了。Linux, python3, pytorch0.3 环境运行的。

**Comment by jinyaqing** [comment]
好的，谢谢！
